//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 220.152984 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_ElyraArmy {
        displayName = "Dominion of Elyra- inf. ";
        side = 1;
        flag = "\a3\Data_F_Enoch\Flags\flag_EAF_co.paa";
        icon = "\a3\Data_F_Enoch\Flags\flag_EAF_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class O_ElyraArmy {
            name = "Dominion of Elyra- inf. ";

            class Infantry {
                name = "Infantry";

                class b_oelyraarmy_infantry_platoon {
                    name = "platoon";
                    side = 1;
                    faction = "O_ElyraArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_OElyraArmy_2nd_LT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_OElyraArmy_SSGT_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_OElyraArmy_SGT_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_OElyraArmy_SGT_01";
                    };
                    class Unit4 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_CPL_01";
                    };
                    class Unit5 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_CPL_01";
                    };
                    class Unit6 {
                        position[] = {5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_CPL_01";
                    };
                    class Unit7 {
                        position[] = {-0,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit8 {
                        position[] = {0,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit9 {
                        position[] = {5,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit10 {
                        position[] = {-5,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit11 {
                        position[] = {10,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit12 {
                        position[] = {-10,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit13 {
                        position[] = {15,-35,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit14 {
                        position[] = {-15,-35,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit15 {
                        position[] = {20,-40,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit16 {
                        position[] = {-20,-40,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit17 {
                        position[] = {25,-45,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit18 {
                        position[] = {-25,-45,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit19 {
                        position[] = {30,-50,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit20 {
                        position[] = {-30,-50,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit21 {
                        position[] = {35,-55,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit22 {
                        position[] = {-35,-55,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                };

                class b_oelyraarmy_infantry_squad {
                    name = "squad";
                    side = 1;
                    faction = "O_ElyraArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_OElyraArmy_SSGT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_SGT_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_CPL_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_CPL_01";
                    };
                    class Unit4 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit5 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit6 {
                        position[] = {5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit7 {
                        position[] = {-0,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit8 {
                        position[] = {0,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit9 {
                        position[] = {5,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit10 {
                        position[] = {-5,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit11 {
                        position[] = {10,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                };

                class b_oelyraarmy_infantry_section {
                    name = "section";
                    side = 1;
                    faction = "O_ElyraArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_OElyraArmy_SGT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_OElyraArmy_PVT_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_T_Officer_F;
    class B_T_Officer_F_OCimport_01 : B_T_Officer_F { scope = 0; class EventHandlers; };
    class B_T_Officer_F_OCimport_02 : B_T_Officer_F_OCimport_01 { class EventHandlers; };


    class B_OElyraArmy_2nd_LT_01 : B_T_Officer_F_OCimport_02 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "2nd LT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_2NDLT";

        linkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"vn_m1895","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"vn_m1895","NORTH_Binocular_Huet"};

        magazines[] = {"vn_m1895_mag","vn_m1895_mag"};
        respawnMagazines[] = {"vn_m1895_mag","vn_m1895_mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"vn_m1895","","","",{"vn_m1895_mag",7},{},""},{"U_NORTH_FIN_M27_Uniform_2NDLT",{}},{"V_NORTH_FIN_Officer_2",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"vn_m1895_mag",10,7}}},{},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_1st_LT_01 : B_OElyraArmy_2nd_LT_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "1st LT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_1STLT_RES";

        linkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"vn_m1895","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"vn_m1895","NORTH_Binocular_Huet"};

        magazines[] = {"vn_m1895_mag","vn_m1895_mag"};
        respawnMagazines[] = {"vn_m1895_mag","vn_m1895_mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"vn_m1895","","","",{"vn_m1895_mag",7},{},""},{"U_NORTH_FIN_M27_Uniform_1STLT_RES",{}},{"V_NORTH_FIN_Officer_2",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"vn_m1895_mag",10,7}}},{},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_SSGT_01 : B_OElyraArmy_1st_LT_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSGT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_SSGT";

        linkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};

        magazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};
        respawnMagazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};

        backpack = "TSGW_French_1914_backpack2";

        ALiVE_orbatCreator_loadout[] = {{"kap_weap_mh_rifle_ol","","kap_mh_bayonet","",{"kap_mh_577_450_mag",1},{},""},{},{},{"U_NORTH_FIN_M27_Uniform_SSGT",{{"kap_mh_577_450_mag",3,1}}},{"V_NORTH_FIN_Rifleman_3",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"kap_mh_577_450_mag",75,1}}},{"TSGW_French_1914_backpack2",{}},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_SGTMAJ_01 : B_OElyraArmy_SSGT_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "SGTMAJ";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_SGTMAJ";

        linkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};

        magazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};
        respawnMagazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};

        backpack = "TSGW_French_1914_backpack2";

        ALiVE_orbatCreator_loadout[] = {{"kap_weap_mh_rifle_ol","","kap_mh_bayonet","",{"kap_mh_577_450_mag",1},{},""},{},{},{"U_NORTH_FIN_M27_Uniform_SGTMAJ",{{"kap_mh_577_450_mag",3,1}}},{"V_NORTH_FIN_Rifleman_3",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"kap_mh_577_450_mag",75,1}}},{"TSGW_French_1914_backpack2",{}},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_SGT_01 : B_OElyraArmy_SGTMAJ_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "SGT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_SGT";

        linkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};

        magazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};
        respawnMagazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};

        backpack = "TSGW_French_1914_backpack2";

        ALiVE_orbatCreator_loadout[] = {{"kap_weap_mh_rifle_ol","","kap_mh_bayonet","",{"kap_mh_577_450_mag",1},{},""},{},{},{"U_NORTH_FIN_M27_Uniform_SGT",{{"kap_mh_577_450_mag",3,1}}},{"V_NORTH_FIN_Rifleman_3",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"kap_mh_577_450_mag",75,1}}},{"TSGW_French_1914_backpack2",{}},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_CPL_01 : B_OElyraArmy_SGT_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "CPL";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_CPL";

        linkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};

        magazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};
        respawnMagazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};

        backpack = "TSGW_French_1914_backpack2";

        ALiVE_orbatCreator_loadout[] = {{"kap_weap_mh_rifle_ol","","kap_mh_bayonet","",{"kap_mh_577_450_mag",1},{},""},{},{},{"U_NORTH_FIN_M27_Uniform_CPL",{{"kap_mh_577_450_mag",3,1}}},{"V_NORTH_FIN_Rifleman_3",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"kap_mh_577_450_mag",75,1}}},{"TSGW_French_1914_backpack2",{}},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_PVT_01 : B_OElyraArmy_CPL_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "PVT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_Private_2";

        linkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Rifleman_3","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"kap_weap_mh_rifle_ol","NORTH_Binocular_Huet"};

        magazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};
        respawnMagazines[] = {"kap_mh_577_450_mag","kap_mh_577_450_mag"};

        backpack = "TSGW_French_1914_backpack2";

        ALiVE_orbatCreator_loadout[] = {{"kap_weap_mh_rifle_ol","","kap_mh_bayonet","",{"kap_mh_577_450_mag",1},{},""},{},{},{"U_NORTH_FIN_M27_Uniform_Private_2",{{"kap_mh_577_450_mag",3,1}}},{"V_NORTH_FIN_Rifleman_3",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"kap_mh_577_450_mag",75,1}}},{"TSGW_French_1914_backpack2",{}},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_OElyraArmy_CPT_01 : B_OElyraArmy_1st_LT_01 {
        author = "Nicole the terrible";
        scope = 2;
        scopeCurator = 2;
        displayName = "CPT";
        side = 1;
        faction = "O_ElyraArmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_casual"};

        uniformClass = "U_NORTH_FIN_M27_Uniform_CPT_RES";

        linkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};
        respawnlinkedItems[] = {"V_NORTH_FIN_Officer_2","H_NORTH_FIN_M27_civilguardhat","ItemMap","NORTH_FIN_Compass","NORTH_FIN_Watch"};

        weapons[] = {"vn_m1895","NORTH_Binocular_Huet"};
        respawnWeapons[] = {"vn_m1895","NORTH_Binocular_Huet"};

        magazines[] = {"vn_m1895_mag","vn_m1895_mag"};
        respawnMagazines[] = {"vn_m1895_mag","vn_m1895_mag"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"vn_m1895","","","",{"vn_m1895_mag",7},{},""},{"U_NORTH_FIN_M27_Uniform_CPT_RES",{}},{"V_NORTH_FIN_Officer_2",{{"ZSN_TrenchWhistle",1},{"ace_flags_red",1},{"ACE_Canteen",1},{"FirstAidKit",1},{"vn_m1895_mag",10,7}}},{},"H_NORTH_FIN_M27_civilguardhat","",{"NORTH_Binocular_Huet","","","",{},{},""},{"ItemMap","","","NORTH_FIN_Compass","NORTH_FIN_Watch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};